<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MNCTVN05589" name="Chat Test" tests="4" failures="4" timestamp="9 Jun 2020 15:03:23 GMT" time="201.738" errors="0">
  <testcase name="" time="94.001" classname="test.Test_Chat">
    <failure type="java.lang.AssertionError" message="expected [dikakoko] but found [dikakokodikakoko]">
      <![CDATA[java.lang.AssertionError: expected [dikakoko] but found [dikakokodikakoko]
	at object.Chats.validateUsername(Chats.java:84)
	at testcases.Chat.chatRcti(Chat.java:30)
	at test.Test_Chat.chat_beforeLoginRCTI(Test_Chat.java:16)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="31.491" classname="test.Test_Chat">
    <failure type="java.lang.AssertionError" message="expected [dikakoko] but found [dikakokodikakoko]">
      <![CDATA[java.lang.AssertionError: expected [dikakoko] but found [dikakokodikakoko]
	at object.Chats.validateUsername(Chats.java:84)
	at testcases.Chat.chatMnctv(Chat.java:48)
	at test.Test_Chat.chat_beforeLoginMNCTV(Test_Chat.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="31.144" classname="test.Test_Chat">
    <failure type="java.lang.AssertionError" message="expected [dikakoko] but found [dikakokodikakoko]">
      <![CDATA[java.lang.AssertionError: expected [dikakoko] but found [dikakokodikakoko]
	at object.Chats.validateUsername(Chats.java:84)
	at testcases.Chat.chatGtv(Chat.java:66)
	at test.Test_Chat.chat_beforeLoginGTV(Test_Chat.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="31.077" classname="test.Test_Chat">
    <failure type="java.lang.AssertionError" message="expected [dikakoko] but found [dikakokodikakoko]">
      <![CDATA[java.lang.AssertionError: expected [dikakoko] but found [dikakokodikakoko]
	at object.Chats.validateUsername(Chats.java:84)
	at testcases.Chat.chatInews(Chat.java:84)
	at test.Test_Chat.chat_beforeLoginINEWS(Test_Chat.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!--  -->
</testsuite> <!-- Chat Test -->
