<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MNCTVN05589" name="test.Test_Mylist" tests="1" failures="1" timestamp="9 Jun 2020 14:02:27 GMT" time="79.917" errors="0">
  <testcase name="mylist_addByAccountLogin" time="79.917" classname="test.Test_Mylist">
    <failure type="java.lang.AssertionError" message="expected [‌] but found [dibayarlunas1video]">
      <![CDATA[java.lang.AssertionError: expected [‌] but found [dibayarlunas1video]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at object.Mylists.validateMylistAdded(Mylists.java:113)
	at testcases.Mylist.addMylistByAccountLogin(Mylist.java:25)
	at test.Test_Mylist.mylist_addByAccountLogin(Test_Mylist.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- mylist_addByAccountLogin -->
</testsuite> <!-- test.Test_Mylist -->
